spring.application.name=university

# ????????? H2 ???? ??????
spring.datasource.url=jdbc:h2:mem:university
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ?????????? SQL ??????? ? ??????? (?????? ??? ???????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?????????????? ???????? ?????? ?? Entity ???????
spring.jpa.hibernate.ddl-auto=create-drop

# ??????? H2 (???????? ?? http://localhost:8080/h2-console)
spring.h2.console.enabled=true