-- Таблица "Преподаватели"
CREATE TABLE teachers
(
    TEACHER_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME    VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    EMAIL        VARCHAR(50)
);

-- Таблица "Курсы"
CREATE TABLE courses
(
    COURSE_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    COURSE_NAME VARCHAR(100) NOT NULL,
    TEACHER_ID  BIGINT NOT NULL,
    DESCRIPTION TEXT,
    FOREIGN KEY (TEACHER_ID) REFERENCES teachers (TEACHER_ID)
);

-- Таблица "Студенты"
CREATE TABLE students
(
    STUDENT_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME    VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    EMAIL        VARCHAR(50)
);

-- Таблица для связи Многие-ко-многим (Student ↔ Course)
CREATE TABLE student_courses
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID BIGINT NOT NULL,
    COURSE_ID  BIGINT NOT NULL,
    ENROLLMENT_DATE DATE DEFAULT CURRENT_DATE,
    GRADE INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES students (STUDENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES courses (COURSE_ID) ON DELETE CASCADE,
    UNIQUE(STUDENT_ID, COURSE_ID)
);